import turtle
s = turtle.Screen()
s.setup(width=1000,height=1000)
turtle.title("Lipsa de Comunicare")
tr = turtle.Turtle()
tr.hideturtle()
def RoomContur(sx,sy):
    def trstart(offx,offy):
        tr.pu()
        tr.goto(sx+offx,sy+offy)
        tr.pd()
    tr.pu()
    tr.goto(sx,sy)
    tr.pd()
    tr.pencolor('black')
    tr.setheading(tr.towards(0,0))
    tr.pensize(3)
    tr.rt(45)
    tr.forward(400)
    trstart(0,0)
    tr.lt(90)
    tr.forward(400)
    trstart(0,0)
    tr.setheading(tr.towards(0,0))
    tr.fd(30)
    tr.rt(45)
    tr.forward(400)
    tr.rt(135)
    tr.fd(30)
    trstart(0,30)
    
RoomContur(0,-100)
a=0
input(a)